<?php
$SETTINGS_MGMT_BANNER='ISMS Test Site';
$SETTINGS_MGMT_LOGO='MGMT-IVirtualWriter-small.png';
$SETTINGS_MGMT_FOOTER='mgmt footer';
$SETTINGS_WRITERS_BANNER='ISMS Writer Test Site';
$SETTINGS_WRITERS_LOGO='WRITERS-IVirtualWriter-small.png';
$SETTINGS_WRITERS_FOOTER='writers footer';
$SETTINGS_SUPPORTEMAIL='t@email.com';
$SETTINGS_SUPPORTNUMBER='000-000-0000';
$SETTINGS_TAXFAXNUMBER='000-000-0000';
