# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2016-02-13 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbkeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(-1, b'Unknown'), (1, b'Register'), (2, b'Check In'), (3, b'Add Organization'), (4, b'Add User'), (5, b'Add Team'), (6, b'Join'), (7, b'Leave'), (8, b'Station Status'), (9, b'Unregister'), (10, b'At Waypoint'), (11, b'Start Challenge'), (12, b'Submit'), (13, b'Register (2015)'), (14, b'At Waypoint (2015)'), (15, b'Start Challenge (2015)'), (16, b'Submit (2015)'), (17, b'Dock'), (18, b'Latch'), (19, b'Open'), (20, b'Secure'), (21, b'Return'), (22, b'Event Concluded'), (23, b'Event Started'), (24, b'Log Message'), (25, b'Reset Team')], default=-1)),
                ('status', models.SmallIntegerField(choices=[(-10, b'Fatal'), (-5, b'Warning'), (-1, b'Fail'), (0, b'Unknown'), (1, b'Success'), (5, b'Info'), (3, b'Detail')], default=0)),
                ('data', models.TextField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PiStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=60)),
                ('station_type', models.CharField(choices=[(b'Unknown', b'Unknown'), (b'Launch', b'Launch'), (b'Dock', b'Dock'), (b'Secure', b'Secure'), (b'Return', b'Return to Earth')], default=b'Unknown', max_length=20)),
                ('station_id', models.CharField(blank=True, max_length=20)),
                ('serial_num', models.CharField(blank=True, max_length=50, unique=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('joined', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='piservice.PiEvent')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pievent',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='piservice.PiStation'),
        ),
        migrations.AddField(
            model_name='pievent',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbkeeper.Team'),
        ),
    ]
