# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piservice', '0012_auto_20160131_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pievent',
            name='type',
            field=models.SmallIntegerField(choices=[(-1, b'Unknown'), (1, b'Register'), (2, b'Check In'), (3, b'Add Organization'), (4, b'Add User'), (5, b'Add Team'), (6, b'Join'), (7, b'Leave'), (8, b'Station Status'), (9, b'Unregister'), (10, b'At Waypoint'), (11, b'Start Challenge'), (12, b'Submit'), (13, b'Register (2015)'), (14, b'At Waypoint (2015)'), (15, b'Start Challenge (2015)'), (16, b'Submit (2015)'), (17, b'Dock'), (18, b'Latch'), (19, b'Open'), (20, b'Secure'), (21, b'Return')], default=-1),
        ),
    ]
