# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbkeeper', '0007_auto_20151217_0424'),
        ('dbkeeper', '0008_auto_20151120_2121'),
    ]

    operations = [
    ]
