# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbkeeper', '0010_auto_20160107_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
