<?php
$SYSCONFIG_WEBDOMAIN='http://localhost';
$SYSCONFIG_WEBFOLDER='/m/';
$SYSCONFIG_DBHOST='localhost';
$SYSCONFIG_DBNAME='m';
$SYSCONFIG_DBUSER='root';
$SYSCONFIG_DBPASS='$$##zxcv';
$SYSCONFIG_DEBUG=1;
$SYSCONFIG_SENDMAIL=0;
$SYSCONFIG_LOGLEVEL=5;
$SYSCONFIG_DATASET=1;  // 1 for test data 0 for real
