<?php
$SYSCONFIG_WEBFOLDER='/m/';
$SYSCONFIG_WEBDOMAIN='http://metsys.dlinkddns.com';
$SYSCONFIG_DBHOST='localhost';
$SYSCONFIG_DBNAME='m';
$SYSCONFIG_DBUSER='root';
$SYSCONFIG_DBPASS='';
$SYSCONFIG_DBPASS='$$##zxcv';
$SYSCONFIG_DEBUG=1;
$SYSCONFIG_SENDMAIL=1;

